insurance_register_app/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib.auth.decorators import permission_required, login_required

from .views import \
    import_policies_act_confirm_delivery, \
    import_policies_act_in_branch, import_policies_act_delete, \
    import_policies_print_dispatch_act, import_policies_act_view, policies_import, \
    PoliciesListView, ClientListView, client_edit, main_page, \
    policy_issue, PaperEdit, report, invoices_report, InsuredEdit, \
    api_recipients_list, api_policies_list, api_policy_get, \
    utilization_act_view, UtilizationActsListView, utilization_act_add, \
    utilization_act_del, api_utilization_acts_list, api_utilization_act_edit, \
    ExpensesListView, ExpenseCreate, ExpenseDelete, ExpenseUpdate, stats_view, \
    PolicyDelete, policy_corrupted, policy_cancel, docs, VehicleBrandListView, \
    VehicleBrandCreate, VehicleBrandDelete, VehicleBrandUpdate, \
    import_policies_print_accept_act, client_add, utilization_act_print, \
    api_policy_edit, ImportantPoliciesListView, \
    api_unseen_important_policies_list, ClientDelete, \
    audit_logs, InsuredAuditDetailView

paper_urls = None
vehicle_brands_urls = [
    url(r'^dobavit/?',
        permission_required('insurance_register_app.add_vehiclebrand')(
            VehicleBrandCreate.as_view()), name='add'),
    url(r'^(?P<pk>[0-9]+)/udalit/?',
        permission_required('insurance_register_app.delete_vehiclebrand')(
            VehicleBrandDelete.as_view()), name='delete'),
    url(r'^(?P<pk>[0-9]+)/?',
        permission_required('insurance_register_app.change_vehiclebrand')(
            VehicleBrandUpdate.as_view()), name='edit'),
    url(r'^',
        login_required(VehicleBrandListView.as_view()), name='list'),
]
audit_logs_urls = [
    url(r'^(?P<audited_type>[0-9]+)/(?P<audited_id>[0-9]+)/?', InsuredAuditDetailView.as_view(), name='details'),
    url(r'^', audit_logs, name='list'),
]
policies_import_urls = [
    url(r'^akt/', include([url(r'^(?P<act_id>[0-9]+)/udalit$',
                               import_policies_act_delete, name='delete'),
                           url(r'^(?P<act_id>[0-9]+)/podtverdit$',
                               import_policies_act_confirm_delivery,
                               name='approve'),
                           url(r'^(?P<act_id>[0-9]+)/v_filiale$',
                               import_policies_act_in_branch,
                               name='in_branch'),
                           url(r'^(?P<act_id>[0-9]+)/pechat_otpravki$',
                               import_policies_print_dispatch_act, name='dispatch_print'),
                           url(r'^(?P<act_id>[0-9]+)/pechat_priema$',
                               import_policies_print_accept_act, name='accept_print'),
                           url(r'^(?P<act_id>[0-9]+)$',
                               import_policies_act_view, name='view'), ],
                          namespace='act')),
    url(r'^', policies_import, name='index'), ]

utilization_acts = [
    url(r'^dobavit$', utilization_act_add, name='add'),
    url(r'^(?P<act_id>[0-9]+)/udalit/?', utilization_act_del, name='delete'),
    url(r'^(?P<act_id>[0-9]+)/pechat/?', utilization_act_print, name='print'),
    url(r'^(?P<act_id>[0-9]+)/?', utilization_act_view, name='view'),
    url(r'^', UtilizationActsListView.as_view(), name='list'),
]

policies_urls = [
    url(r'^(?P<pk>[0-9]+)/udalit/?', PolicyDelete.as_view(), name='delete'),
    url(r'^(?P<policy_id>[0-9]+)/isporchen/?', policy_corrupted,
        name='corrupt'),
    url(r'^(?P<policy_id>[0-9]+)/rastorjen/?', policy_cancel,
        name='cancel'),
    url(r'^(?P<policy_id>[0-9]+)/?', policy_issue, name='edit'),
    url(r'^(?P<insured_type>\w+)/(?P<insured_id>[0-9]+)/(?P<policy_type>\w+)(?:/prolongs/(?P<prolong_id>\w+))?/?',
        policy_issue, name='add'),
    url(r'^oshibki', ImportantPoliciesListView.as_view(), name='important-list'),
    url(r'^', PoliciesListView.as_view(), name='list'),
]

urlpatterns = [
    url(r'^import_polisov/', include(policies_import_urls, namespace='policies_import')),
    url(r'^policies/', include(policies_urls, namespace='policies')),

    url(r'^rashody/', include([
        url(r'^add/?', ExpenseCreate.as_view(), name='add'),
        url(r'^(?P<pk>[0-9]+)/udalit/?', ExpenseDelete.as_view(), name='delete'),
        url(r'^(?P<pk>[0-9]+)/?', ExpenseUpdate.as_view(), name='edit'),
        url(r'^', ExpensesListView.as_view(), name='list'),
    ], namespace='expenses')),

    url(r'^akty_spisania/', include(utilization_acts, namespace='utilization_act')),

    url(r'^clienty/', include([
        url(r'^$', ClientListView.as_view(), name='list'),
        url(r'^(?P<client_id>[0-9]+)/', include([
            url(r'^$', client_edit, name='edit'),
            url(r'^udalit$', ClientDelete.as_view(), name='delete'),

            url(r'^dokumenty/', include([
                url(r'^(?P<paper_id>[0-9]+)/delete',
                    PaperEdit.as_view(), {'delete': True}, name='delete'),
                url(r'^(?:(?P<paper_id>[0-9]+))?', PaperEdit.as_view(), name='edit'),
            ], namespace='papers')),

            url(r'^insured/', include([
                url(r'^(?P<insured_type>\w+)/(?:(?P<insured_id>[0-9]+))/delete',
                    InsuredEdit.as_view(), {'delete': True}, name='delete'),
                url(r'^(?P<insured_type>\w+)/(?:(?P<insured_id>[0-9]+))?',
                    InsuredEdit.as_view(), name='edit'),
            ], namespace='insured')),
        ])),
        url(r'^dobavit/(?P<client_type>\w)$', client_add, name='add'),
    ], namespace='clients')),

    url(r'^api/', include([
        url(r'^policies$', api_policies_list, name='api-policies-list'),
        url(r'^policies/unseen-important$', api_unseen_important_policies_list, name='api-unseen-important-policies-list'),
        url(r'^policies/(?P<policy_id>[0-9]+)/$', api_policy_get, name='api-policy-get'),
        url(r'^policies/(?P<policy_id>[0-9]+)/edit$', api_policy_edit, name='api-policy-edit'),
        url(r'^recipients$', api_recipients_list, name='api-recipients-list'),
        url(r'^utilization-acts$', api_utilization_acts_list, name='api-utilization-acts-list'),
        url(r'^utilization-act/edit$', api_utilization_act_edit,
            name='api-utilization-act-edit'),
    ])),

    url(r'^brendy/', include(vehicle_brands_urls, namespace='vehicle_brands')),

    url(r'^report', report, name='report'),
    url(r'^scheta_report', invoices_report, name='invoices_report'),
    url(r'^documentacia$', docs, name='docs'),
    url(r'^statistika$', stats_view, name='view_statistics'),
    url(r'^jurnal/', include(audit_logs_urls, namespace='logs')),
    url(r'^$', main_page, name='index'),
]

insurance_register_project/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin, auth
from django.conf import settings
from django.urls import reverse

handler403 = 'insurance_register_app.views.handler403_view'
handler404 = 'insurance_register_app.views.handler404_view'
handler500 = 'insurance_register_app.views.handler500_view'

urlpatterns = [
    # url(r'^accounts/login/$', auth.login,
    #     {'template_name': 'admin/login.html'}),
    # url(r'^accounts/logout/$', auth.logout, {'next_page': reverse('index')}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'^', include('insurance_register_app.urls'))
]

insurance_register_app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
from collections import OrderedDict
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import translation
from django.conf import settings

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import ObjectDoesNotExist, NON_FIELD_ERRORS
from django.db.models import Q, Count, Sum, Case, CharField, Value, When
from django.db.models.functions import Concat
from django.http import HttpResponseForbidden
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PoliciesImportForm, PolicyForm, PaperForm, \
    PoliciesReportForm, InvoicesReportForm, InsuredForm, ExpenseEditForm, \
    ExpensesListForm, StatisticsListForm, PolicyCorruptedForm, PolicyCancelForm, \
    VehicleBrandEditForm, ClientOrganizationForm, ClientPersonForm, \
    ClientListForm

from .models import Insured, Expense, VehicleBrand, \
    Policy, Branch, InsuranceCompany, PoliciesImportAct, \
    User, Client, Paper, InsuredVehicle, UtilizationAct, Statistics, \
    get_object_by_class_and_pk, PROLONGED_TYPES, PROLONGED_TYPE_N, PROLONGED_TYPE_P, \
    AuditLog, AuditedObjectMixin, Invoice


@login_required
def main_page(request):
    ctx = {}
    user = request.user

    return redirect(reverse_lazy(user.start_url))


@method_decorator(login_required, name='dispatch')
class PoliciesListView(ListView):
    model = Policy
    paginate_by = 20
    context_object_name = 'policies'
    template_name = 'policies/list.html'

    def get_queryset(self):
        policies = Policy.objects
        branch = self.request.user.filtering_branch
        if branch:
            policies = policies.filter(branch=branch)

        return policies.all()

        # def policies_list(self, request):
        #     ctx = {}
        #     user = request.user
        #
        #     policies = Policy.objects
        #     if user.is_operator:
        #         acts = PoliciesImportAct.objects.filter(branch=user.branch)
        #         policies = policies.filter(act__in=acts)
        #     policies = policies.all()
        #
        #     ctx['policies'] = policies
        #
        #     return render(request, , ctx)


@method_decorator(login_required, name='dispatch')
class ImportantPoliciesListView(ListView):
    model = Policy
    paginate_by = 20
    context_object_name = 'policies'
    template_name = 'policies/list_important.html'

    def get_queryset(self):
        policies = Policy.objects.filter(important=True)
        branch = self.request.user.filtering_branch
        if branch:
            policies = policies.filter(branch=branch)

        self.request.user.importants_last_reading_time = datetime.now()
        self.request.user.save()

        return policies.all()


@login_required
def policy_corrupted(request, policy_id):
    ctx = {}
    user = request.user
    policy = get_object_or_404(Policy, pk=policy_id)
    # if not request.user.check_user_access(policy.branch):
    #     return HttpResponseForbidden()

    form = PolicyCorruptedForm()

    if policy.STATUS_CORRUPTED == policy.status:
        message = _('Policy "%s" is corrupted') % policy
    elif policy.STATUS_CORRUPTED_CANDIDAT == policy.status:
        message = _('Confirm that policy "%s" is corrupted') % policy
    else:
        message = _('Declare policy "%s" as corrupted') % policy

    if request.method == 'POST':
        form = PolicyCorruptedForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['agree']:
                if policy.STATUS_CORRUPTED_CANDIDAT == policy.status:
                    policy.status = policy.STATUS_CORRUPTED
                else:
                    policy.status = policy.STATUS_CORRUPTED_CANDIDAT
            else:
                if policy.insured:
                    policy.status = policy.STATUS_ISSUED
                else:
                    policy.status = policy.STATUS_NEW

            policy.save()
            return redirect('policies:edit', policy_id=policy.id)

    ctx['form'] = form
    ctx['policy'] = policy
    ctx['message'] = message

    return render(request, 'policies/trash.html', ctx)

@login_required
def policy_cancel(request, policy_id):
    ctx = {}
    user = request.user
    policy = get_object_or_404(Policy, pk=policy_id)
    # if not request.user.check_user_access(policy.branch):
    #     return HttpResponseForbidden()

    form = PolicyCancelForm()

    if policy.STATUS_CANCELED == policy.status:
        message = _('Policy "%s" is canceled') % policy
    else:
        message = _('Declare policy "%s" as canceled') % policy

    if request.method == 'POST':
        form = PolicyCancelForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['agree']:
                policy.status = policy.STATUS_CANCELED
            else:
                policy.status = policy.STATUS_ISSUED

            policy.save()
            return redirect('policies:edit', policy_id=policy.id)

    ctx['form'] = form
    ctx['policy'] = policy
    ctx['message'] = message

    return render(request, 'policies/cancel.html', ctx)


@require_POST
@login_required
def utilization_act_add(request):
    res = {}
    act = UtilizationAct()
    act.save()
    res['status'] = 'ok'

    return JsonResponse(res)


@require_POST
@login_required
def utilization_act_del(request, act_id):
    res = {}
    try:
        act = UtilizationAct.objects.get(pk=act_id)
        act.delete()
        res['status'] = 'ok'
    except ObjectDoesNotExist:
        res['status'] = 'error'
        res['message'] = _('Act not found: ') + act_id

    return JsonResponse(res)


@login_required
def utilization_act_view(request, act_id):
    ctx = {}
    act = get_object_or_404(UtilizationAct, pk=act_id)  # type: UtilizationAct
    ctx['act'] = act

    return render(request, 'utilization_act/view.html', ctx)


@login_required()
def utilization_act_print(request, act_id):
    act = get_object_or_404(UtilizationAct, pk=act_id)

    policies = sorted(act.policies_all, key=lambda policy: policy.full_number)

    return render(request, 'utilization_act/print.html', {
        'act': act,
        'policies': policies,
    })


@require_POST
@login_required
def api_utilization_act_edit(request):
    res = {}
    post_data = json.loads(request.body)
    act_pk = None
    act = None
    message = _('Successfully removed from any acts')
    if ('act_id' in post_data) and post_data['act_id']:
        act_pk = post_data['act_id']
        act = get_object_or_404(UtilizationAct,
                                pk=act_pk)  # type: UtilizationAct
        message = _("Successfully attached to act #%d") % act.pk

    if 'policies' in post_data:
        for policy_id in list(post_data['policies'].values()):
            policy = Policy.objects.get(pk=policy_id)
            policy.utilization_act = act
            if act is None:
                if policy.insured:
                    policy.status = policy.STATUS_ISSUED
                else:
                    policy.status = policy.STATUS_NEW
            policy.save()

    if 'acts' in post_data:
        for child_act_id in list(post_data['acts'].values()):
            if child_act_id != act_pk:
                child_act = UtilizationAct.objects.get(
                    pk=child_act_id)  # type: UtilizationAct
                child_act.parent_act = act
                child_act.save()

    res['status'] = 'ok'
    res['message'] = message

    return JsonResponse(res)


@method_decorator(login_required, name='dispatch')
class UtilizationActsListView(ListView):
    model = UtilizationAct
    paginate_by = 20
    ordering = '-edited_at'
    context_object_name = 'acts'
    template_name = 'utilization_act/list.html'


@method_decorator(login_required, name='dispatch')
class PolicyDelete(DeleteView):
    model = Policy
    template_name = 'policies/delete.html'

    def delete(self, request, *args, **kwargs):
        policy = self.get_object()  # type: Policy
        # if not request.user.check_user_access(policy.branch):
        #     return HttpResponseForbidden()
        url = reverse_lazy('clients:edit', kwargs={
            'client_id': policy.insured.client.pk,
        })
        if not policy.is_readonly:
            policy.delete_method()

        return HttpResponseRedirect(url)


@login_required
def policy_issue(request, insured_type=None, insured_id=None, policy_type=None,
                 policy_id=None, prolong_id=None):
    ctx = {}

    insured = None
    if policy_id:
        policy = get_object_or_404(Policy, pk=policy_id)  # type: Policy
        # if not request.user.check_user_access(policy.branch):
        #     return HttpResponseForbidden()

        if hasattr(policy, 'insured') and policy.insured:
            insured = policy.insured
        if request.GET.get('insured_id'):
            insured = get_object_or_404(InsuredVehicle,
                                        pk=request.GET.get('insured_id'))
            policy.insured = insured

        insured_type = policy.insured.__class__.__name__
        insured_id = policy.insured_id

    else:
        insured_type_cls = Insured.get_class(insured_type)
        insured = get_object_or_404(insured_type_cls,
                                    pk=insured_id)  # type: Insured
        policy = Policy(insured=insured)
        policy.type = policy_type
        if prolong_id:

insurance_register_app/templates/vehicle_brands/delete.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {% block title %}
                        {% trans 'Delete vehicle brand' %}
                    {% endblock %}
                </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    {% if message %}
                        <div class="bg-info">{{ message }}</div>
                    {% endif %}
                    {% for err, err_mess in form.non_field_errors.iteritems %}
                        {{ err_mess|escape }}
                    {% endfor %}

                    <p>{% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>

                    <button type="submit"
                            class="btn btn-success">{% trans 'Yes, delete' %}</button>
                    <a class="btn btn-default" href="{% url "vehicle_brands:edit" pk=object.id %}"
                       role="button">
                        {% trans 'No, return me edit page' %}
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

insurance_register_app/templates/vehicle_brands/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {% block title %}
                        {% if object.id %}
                            {% trans 'Edit vehicle brand' %}
                        {% else %}
                            {% trans 'Add vehicle brand' %}
                        {% endif %}
                    {% endblock %}
                </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    {% if message %}
                        <div class="bg-info">{{ message }}</div>
                    {% endif %}
                    {% for err, err_mess in form.non_field_errors.iteritems %}
                        {{ err_mess|escape }}
                    {% endfor %}

                    {% for field in form %}
                        {% if field.errors %}
                            <script>
                                {% for error in field.errors %}
                                    document.addEventListener('DOMContentLoaded', function () {
                                        $.notify('{{ error|escape }}',
                                            {
                                                clickToHide: true,
                                                autoHide: false,
                                                arrowShow: true
                                            }
                                        );
                                    });
                                {% endfor %}
                            </script>
                        {% endif %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit"
                            class="btn btn-success">{% trans 'Submit' %}</button>
                    {% if object %}
                        <a class="btn btn-danger" href="{% url "vehicle_brands:delete" pk=form.instance.id %}"
                           role="button">{% trans "Delete" %}</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

insurance_register_app/templates/vehicle_brands/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="col-md-offset-2 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">{% trans 'Vehicles brands' %}</h3>

                <a class="btn btn-default pull-right"
                   href="{% url 'vehicle_brands:add' %}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>

                <div class="clearfix"></div>
            </div>

            <table class="table table-bordered table-hover table-condensed">
                <thead>
                <tr style="font-weight: bold">
                    <td class="col-md-1">{% trans '#' %}</td>
                    <td>{% trans 'Title' %}</td>
                    <td>&NonBreakingSpace;</td>
                </tr>
                </thead>
                {% for brand in brands %}
                    <tr>
                        <td>
                            {{ forloop.counter0|add:page_obj.start_index }}
                        </td>
                        <td>
                            {{ brand.title }}
                        </td>
                        <td>
                            <a href="{% url 'vehicle_brands:edit' pk=brand.pk %}">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% include 'pagination.html' %}
        </div>
    </div>

{% endblock %}