insurance_register_app/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib.auth.decorators import permission_required, login_required

from .views import \
    import_policies_act_confirm_delivery, \
    import_policies_act_in_branch, import_policies_act_delete, \
    import_policies_print_dispatch_act, import_policies_act_view, policies_import, \
    PoliciesListView, ClientListView, client_edit, main_page, \
    policy_issue, PaperEdit, report, invoices_report, InsuredEdit, \
    api_recipients_list, api_policies_list, api_policy_get, \
    utilization_act_view, UtilizationActsListView, utilization_act_add, \
    utilization_act_del, api_utilization_acts_list, api_utilization_act_edit, \
    ExpensesListView, ExpenseCreate, ExpenseDelete, ExpenseUpdate, stats_view, \
    PolicyDelete, policy_corrupted, policy_cancel, docs, VehicleBrandListView, \
    VehicleBrandCreate, VehicleBrandDelete, VehicleBrandUpdate, \
    import_policies_print_accept_act, client_add, utilization_act_print, \
    api_policy_edit, ImportantPoliciesListView, \
    api_unseen_important_policies_list, ClientDelete, \
    audit_logs, InsuredAuditDetailView

paper_urls = None
vehicle_brands_urls = [
    url(r'^dobavit/?',
        permission_required('insurance_register_app.add_vehiclebrand')(
            VehicleBrandCreate.as_view()), name='add'),
    url(r'^(?P<pk>[0-9]+)/udalit/?',
        permission_required('insurance_register_app.delete_vehiclebrand')(
            VehicleBrandDelete.as_view()), name='delete'),
    url(r'^(?P<pk>[0-9]+)/?',
        permission_required('insurance_register_app.change_vehiclebrand')(
            VehicleBrandUpdate.as_view()), name='edit'),
    url(r'^',
        login_required(VehicleBrandListView.as_view()), name='list'),
]
audit_logs_urls = [
    url(r'^(?P<audited_type>[0-9]+)/(?P<audited_id>[0-9]+)/?', InsuredAuditDetailView.as_view(), name='details'),
    url(r'^', audit_logs, name='list'),
]
policies_import_urls = [
    url(r'^akt/', include([url(r'^(?P<act_id>[0-9]+)/udalit$',
                               import_policies_act_delete, name='delete'),
                           url(r'^(?P<act_id>[0-9]+)/podtverdit$',
                               import_policies_act_confirm_delivery,
                               name='approve'),
                           url(r'^(?P<act_id>[0-9]+)/v_filiale$',
                               import_policies_act_in_branch,
                               name='in_branch'),
                           url(r'^(?P<act_id>[0-9]+)/pechat_otpravki$',
                               import_policies_print_dispatch_act, name='dispatch_print'),
                           url(r'^(?P<act_id>[0-9]+)/pechat_priema$',
                               import_policies_print_accept_act, name='accept_print'),
                           url(r'^(?P<act_id>[0-9]+)$',
                               import_policies_act_view, name='view'), ],
                          namespace='act')),
    url(r'^', policies_import, name='index'), ]

utilization_acts = [
    url(r'^dobavit$', utilization_act_add, name='add'),
    url(r'^(?P<act_id>[0-9]+)/udalit/?', utilization_act_del, name='delete'),
    url(r'^(?P<act_id>[0-9]+)/pechat/?', utilization_act_print, name='print'),
    url(r'^(?P<act_id>[0-9]+)/?', utilization_act_view, name='view'),
    url(r'^', UtilizationActsListView.as_view(), name='list'),
]

policies_urls = [
    url(r'^(?P<pk>[0-9]+)/udalit/?', PolicyDelete.as_view(), name='delete'),
    url(r'^(?P<policy_id>[0-9]+)/isporchen/?', policy_corrupted,
        name='corrupt'),
    url(r'^(?P<policy_id>[0-9]+)/rastorjen/?', policy_cancel,
        name='cancel'),
    url(r'^(?P<policy_id>[0-9]+)/?', policy_issue, name='edit'),
    url(r'^(?P<insured_type>\w+)/(?P<insured_id>[0-9]+)/(?P<policy_type>\w+)(?:/prolongs/(?P<prolong_id>\w+))?/?',
        policy_issue, name='add'),
    url(r'^oshibki', ImportantPoliciesListView.as_view(), name='important-list'),
    url(r'^', PoliciesListView.as_view(), name='list'),
]

urlpatterns = [
    url(r'^import_polisov/', include(policies_import_urls, namespace='policies_import')),
    url(r'^policies/', include(policies_urls, namespace='policies')),

    url(r'^rashody/', include([
        url(r'^add/?', ExpenseCreate.as_view(), name='add'),
        url(r'^(?P<pk>[0-9]+)/udalit/?', ExpenseDelete.as_view(), name='delete'),
        url(r'^(?P<pk>[0-9]+)/?', ExpenseUpdate.as_view(), name='edit'),
        url(r'^', ExpensesListView.as_view(), name='list'),
    ], namespace='expenses')),

    url(r'^akty_spisania/', include(utilization_acts, namespace='utilization_act')),

    url(r'^clienty/', include([
        url(r'^$', ClientListView.as_view(), name='list'),
        url(r'^(?P<client_id>[0-9]+)/', include([
            url(r'^$', client_edit, name='edit'),
            url(r'^udalit$', ClientDelete.as_view(), name='delete'),

            url(r'^dokumenty/', include([
                url(r'^(?P<paper_id>[0-9]+)/delete',
                    PaperEdit.as_view(), {'delete': True}, name='delete'),
                url(r'^(?:(?P<paper_id>[0-9]+))?', PaperEdit.as_view(), name='edit'),
            ], namespace='papers')),

            url(r'^insured/', include([
                url(r'^(?P<insured_type>\w+)/(?:(?P<insured_id>[0-9]+))/delete',
                    InsuredEdit.as_view(), {'delete': True}, name='delete'),
                url(r'^(?P<insured_type>\w+)/(?:(?P<insured_id>[0-9]+))?',
                    InsuredEdit.as_view(), name='edit'),
            ], namespace='insured')),
        ])),
        url(r'^dobavit/(?P<client_type>\w)$', client_add, name='add'),
    ], namespace='clients')),

    url(r'^api/', include([
        url(r'^policies$', api_policies_list, name='api-policies-list'),
        url(r'^policies/unseen-important$', api_unseen_important_policies_list, name='api-unseen-important-policies-list'),
        url(r'^policies/(?P<policy_id>[0-9]+)/$', api_policy_get, name='api-policy-get'),
        url(r'^policies/(?P<policy_id>[0-9]+)/edit$', api_policy_edit, name='api-policy-edit'),
        url(r'^recipients$', api_recipients_list, name='api-recipients-list'),
        url(r'^utilization-acts$', api_utilization_acts_list, name='api-utilization-acts-list'),
        url(r'^utilization-act/edit$', api_utilization_act_edit,
            name='api-utilization-act-edit'),
    ])),

    url(r'^brendy/', include(vehicle_brands_urls, namespace='vehicle_brands')),

    url(r'^report', report, name='report'),
    url(r'^scheta_report', invoices_report, name='invoices_report'),
    url(r'^documentacia$', docs, name='docs'),
    url(r'^statistika$', stats_view, name='view_statistics'),
    url(r'^jurnal/', include(audit_logs_urls, namespace='logs')),
    url(r'^$', main_page, name='index'),
]

insurance_register_project/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin, auth
from django.conf import settings
from django.urls import reverse

handler403 = 'insurance_register_app.views.handler403_view'
handler404 = 'insurance_register_app.views.handler404_view'
handler500 = 'insurance_register_app.views.handler500_view'

urlpatterns = [
    # url(r'^accounts/login/$', auth.login,
    #     {'template_name': 'admin/login.html'}),
    # url(r'^accounts/logout/$', auth.logout, {'next_page': reverse('index')}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'^', include('insurance_register_app.urls'))
]

insurance_register_app/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import datetime, date
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms.utils import ErrorList
from django.urls import reverse_lazy
from django.utils.dateparse import parse_datetime
from django.db.models import Q
from django.forms.widgets import Input, TextInput, DateInput

from .models import Branch, Policy, PoliciesImportAct, Client, Paper, User, \
    InsuranceType, InsuranceCompany, InsuredVehicle, InsuredRealEstate, \
    InsuredPerson, Expense, ExpenseType, VehicleBrand, PAYMENT_TYPES, PROLONGED_TYPES
from django.utils.translation import ugettext_lazy as _
import pytz
from django.conf import settings


class CustomNameInput(Input):
    def get_context(self, name, value, attrs):
        context = super(CustomInput, self).get_context(name, value, attrs)
        if context['widget']['attrs'].get('name') is not None:
            context['widget']['name'] = context['widget']['attrs']['name']

        return context


class CustomNameTextInput(TextInput, CustomNameInput):
    pass


class CustomNameDateInput(DateInput, CustomNameInput):
    pass


class PoliciesBulkAddForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PoliciesBulkAddForm, self).__init__(*args, **kwargs)
        try:
            self.fields['branch'].initial = Branch.objects.first()
        except:
            pass

    series = forms.CharField(label=_('Policies series'),
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': _(
                                            'Policies series')})
                             )

    branch = forms.ModelChoiceField(queryset=Branch.objects,
                                    label=_('Branches'),
                                    widget=forms.Select(
                                        attrs={'class': 'form-control',
                                               'placeholder': _(
                                                   'Branches')})
                                    )

    ph = _('Numbers only')
    start_policy_number = forms.IntegerField(label=_('First policy number'),
                                             max_value=pow(10, 10),
                                             min_value=0,
                                             widget=forms.NumberInput(
                                                 attrs={'class': 'form-control',
                                                        'placeholder': ph})
                                             )
    finish_policy_number = forms.IntegerField(label=_('Last policy number'),
                                              max_value=pow(10, 10),
                                              min_value=0,

                                              widget=forms.NumberInput(
                                                  attrs={
                                                      'class': 'form-control',
                                                      'placeholder': ph})
                                              )

    def clean(self):
        cleaned_data = super(PoliciesBulkAddForm, self).clean()
        if (cleaned_data['start_policy_number'] >
                cleaned_data['finish_policy_number']):
            self.add_error('start_policy_number',
                           _('Start number have to be less than last one'))
        else:
            return cleaned_data


ph = _('Numbers only')


class PoliciesImportForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(PoliciesImportForm, self).clean()
        first_raw = cleaned_data['first_policy_number']
        last_raw = cleaned_data['last_policy_number']
        if len(first_raw) != len(last_raw):
            raise forms.ValidationError({
                'first_policy_number': forms.ValidationError(
                    _(
                        'Policies numbers have different '
                        'lengths: %(first)s and %(last)s'),
                    code='incorrect_numbers_length',
                    params={'first': first_raw, 'last': last_raw, }
                ),
            })

        first = int(first_raw.lstrip('0'))
        last = int(last_raw.lstrip('0'))
        if first > last:
            raise forms.ValidationError({
                'first_policy_number': forms.ValidationError(
                    _('First policy (%(first)s) can not have '
                      'larger number then last one (%(last)s)'),
                    code='incorrect_numbers_first_is_bigger',
                    params={'first': first_raw, 'last': last_raw, },
                ),
            })

        return cleaned_data

    class Meta:
        model = PoliciesImportAct
        fields = ['series', 'first_policy_number', 'last_policy_number',
                  'branch', 'recipient', 'company', 'type', 'comment']

        widgets = {
            'first_policy_number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': ph}),
            'last_policy_number': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': ph}),
            'series': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': _('Series')}),
            'branch': forms.Select(
                attrs={'class': 'form-control', 'placeholder': _('Branch')}),
            'recipient': forms.Select(
                attrs={'class': 'form-control', 'placeholder': _('Recipient'),
                       'id': 'id_recipient_select2'
                       }),
            'company': forms.Select(
                attrs={'class': 'form-control', 'placeholder': _('Company')}),
            'type': forms.Select(
                attrs={'class': 'form-control', 'placeholder': _('Type')}),
            'comment': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': _('Comment')}),
        }


class PolicyCorruptedForm(forms.Form):
    agree = forms.BooleanField(initial=True, widget=forms.HiddenInput(),
                               required=False)


class PolicyCancelForm(forms.Form):
    agree = forms.BooleanField(initial=True, widget=forms.HiddenInput(),
                               required=False)


class HtmlErrorList(ErrorList):
    error_list_class = 'list-group'
    error_item_class = 'list-group-item list-group-item-danger'

    def __str__(self):
        return self.as_html()

    def __unicode__(self):
        return self.as_html()

    def as_html(self):
        if not self:
            return ''

        errors = '<div><ol class="%s">%s</ol></div>' % (
            self.error_list_class,
            ''.join(['<li class="%s">%s</li>' % (self.error_item_class, e) for e in self]),
        )

        return errors


class ClientForm(forms.ModelForm):

    # MAX_SIMILAR_CLIENTS_COUNT = 10

    # def clean(self):
    #     data = super(ClientForm, self).clean()
    #     clients = Client.objects
    #     for field in self.unique_fields:
    #         if field in data and data[field]:
    #             dict = {field + '__icontains': data[field]}
    #             q_object = Q(**dict)
    #             clients = clients.filter(q_object)
    #
    #     clients = clients.all()
    #     if len(clients):
    #         self._errors[NON_FIELD_ERRORS] = HtmlErrorList()
    #         if len(clients) > self.MAX_SIMILAR_CLIENTS_COUNT:
    #             raise forms.ValidationError(
    #                 _('Found %(count)d similar clients. You entered too few data?'),
    #                 code='max_similar_clients_count_overcome',
    #                 params={'count': len(clients), }
    #             )
    #
    #         errors = []
    #         for client in clients:
    #             errors.append(forms.ValidationError(
    #                 _('Found similar client: <a href="%(url)s">%(client)s</a>'),
    #                 code='found_similar_clients',
    #                 params={
    #                     'url': reverse_lazy('clients:edit',
    #                                         kwargs={'client_id': client.pk}),
    #                     'client': client.full_name,
    #                 }
    #             ))
    #
    #         raise forms.ValidationError(errors)
    #
    #     return data

    @property
    def unique_fields(self):
        return []

    class Meta:
        model = Client
        fields = []

        widgets = {}


class ClientPersonForm(ClientForm):
    @property
    def unique_fields(self):
        return ['last_name', 'first_name', 'patronymic_name', 'phone']

    class Meta:
        model = Client
        fields = [
            'last_name', 'first_name', 'patronymic_name', 'date_of_birth',
            'phone', 'comment', ]

        widgets = {
            'last_name': forms.TextInput(
                attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(
                attrs={'class': 'form-control'}),
            'patronymic_name': forms.TextInput(
                attrs={'class': 'form-control'}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(
                format='%d.%m.%Y',
                attrs={
                    'class': 'form-control datepicker-here',
                    # 'data-date-format': 'dd.mm.yyyy',
                }),
            'comment': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': _('Comment')}),
        }


class ClientOrganizationForm(ClientForm):
    @property
    def unique_fields(self):
        return ['title', 'tax_number', 'phone', ]

    class Meta:
        model = Client
        fields = ['title', 'tax_number', 'address_legal', 'address_actual',
                  'phone', 'comment', ]

        widgets = {

insurance_register_app/templates/policies_import/act/accept_print.html
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>

<table class="table" border="1pxs">
    <h2>{{ act_title }}</h2>
    {% for field in act.get_print_fields %}
        <tr>
            <th>
                {{ field.name }}
            </th>
            <td>
                {{ field.value }}
            </td>
        </tr>
    {% endfor %}
</table>

</body>
</html>

insurance_register_app/templates/policies_import/act/dispatch_print.html
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>

<table class="table" border="1pxs">
    <h2>{{ act_title }}</h2>
    {% for field in act.get_print_fields %}
        <tr>
            <th>
                {{ field.name }}
            </th>
            <td>
                {{ field.value }}
            </td>
        </tr>
    {% endfor %}
</table>

</body>
</html>

insurance_register_app/templates/policies_import/act/form.html
{% load i18n %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            {% block title %}
                {% trans 'Add act' %}
            {% endblock %}
        </h3>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}

            {% if message %}
                <div class="bg-info">{{ message }}</div>
            {% endif %}
            {% for err, err_mess in policies_import_form.non_field_errors.iteritems %}
                {{ err_mess|escape }}
            {% endfor %}

            {% for field in policies_import_form %}
                {% if field.errors %}
                    <script>
                        {% for error in field.errors %}
                            document.addEventListener('DOMContentLoaded', function () {
                                $.notify('{{ error|escape }}',
                                    {
                                        clickToHide: true,
                                        autoHide: false,
                                        arrowShow: true
                                    }
                                );
                            });
                        {% endfor %}
                    </script>
                {% endif %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var recipientSelect = $('#id_recipient_select2');
                    var branchSelect = $('#id_branch');
                    var branch_changed = function (e) {
                        $.ajax({
                            url: "{% url 'api-recipients-list' %}",
                            dataType: 'json',
                            delay: 250,
                                data: {
                                    'branch_id': e.target.value
                                },
                            cache: true
                        }).done(function (data) {
                            recipientSelect
                                .find('option')
                                .remove()
                                .end();
                            var recipients = data['data'];
                            recipients.forEach(function (recipient) {
                                if (recipient['branch_id'] == branchSelect.val()) {
                                    var opt = "<option value=" + recipient['id'] + ">" +
                                        recipient['last_name'] + ' ' + recipient['first_name'] +
                                        "</option>";
                                    recipientSelect.append(opt);
                                }
                            });

                        });
                    };
                    branchSelect.change(function (e) {
                        branch_changed(e);
                    });
                    branchSelect.change();


                });
            </script>
            <button type="submit"
                    class="btn btn-default">{% trans 'Submit' %}</button>

        </form>
    </div>
</div>

insurance_register_app/templates/policies_import/act/view.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="col-md-offset-3 col-md-6">
        <table class="table table-bordered">
            {% for field in act.get_print_fields %}
                <tr>
                    <th>
                        {{ field.name }}
                    </th>
                    <td>
                        {{ field.value }}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% if btn %}
            <form method="post" action="{{ btn.url }}">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">{{ btn.title }}</button>
            </form>
        {% endif %}
        {% if perms.insurance_register_app.delete_policiesimportact %}
            <form method="post"
                  action="{% url 'policies_import:act:delete' act_id=act.id %}">
                {% csrf_token %}
                <button type="submit"
                        class="btn btn-default">{% trans 'Delete' %}</button>
            </form>
        {% endif %}
        {% if perms.insurance_register_app.import_policies_act_print %}
            <a target="_blank" role="button" class="btn btn-default"
               href="{% url 'policies_import:act:dispatch_print' act_id=act.id  %}">
                {% trans 'Dispatch print' %}
            </a>
        {% endif %}
        <a target="_blank" role="button" class="btn btn-default"
           href="{% url 'policies_import:act:accept_print' act_id=act.id  %}">
            {% trans 'Accept print' %}
        </a>
    </div>
{% endblock %}